import { LobbyProvider } from "@/hooks/use-lobby";
import { UserProvider } from "@/hooks/use-user";
import { auth } from "@/lib/auth";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Pixelify_Sans } from "next/font/google";
import { headers } from "next/headers";
import "./globals.css";

const pixelify = Pixelify_Sans({
  variable: "--font-pixelify-sans",
  subsets: ["latin"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Mystique",
  description: "Generated by create next app",
};

export default async ({ children }: Readonly<{ children: React.ReactNode }>) => {
  const session = await auth.api.getSession({ headers: await headers() });
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${pixelify.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          disableTransitionOnChange
          enableSystem
        >
          <UserProvider user={session?.user}>
            <LobbyProvider>{children}</LobbyProvider>
          </UserProvider>
        </ThemeProvider>
      </body>
    </html>
  );
};
