import { db, schema } from "../seed";
import {
  arrow,
  blessing,
  blizzard,
  chainLightning,
  cleave,
  crush,
  dodge,
  fireball,
  focusBolt,
  freeze,
  greaterHeal,
  hack,
  heal,
  impale,
  inferno,
  multishot,
  pierce,
  pierceShot,
  pummel,
  regenerate,
  rend,
  riposte,
  silence,
  slash,
  smite,
  snipe,
  stab,
  strike,
  stun,
  thunder,
  toxicCloud,
  venom,
  volley,
  whirlwind,
} from "./abilities";

const ITEMS: (typeof schema.item.$inferInsert)[] = [
  {
    name: "Training Sword",
    type: "weapon",
    value: 8,
    weight: 2,
    armor: null,
    abilities: [strike(2, 4)],
    requiremnts: { strength: 4, dexterity: 3, constitution: null, intelligence: null },
  },
  {
    name: "Rough Dagger",
    type: "weapon",
    value: 7,
    weight: 1,
    armor: null,
    abilities: [stab(1, 5)],
    requiremnts: { strength: 2, dexterity: 5, constitution: null, intelligence: null },
  },
  {
    name: "Initiate Wand",
    type: "weapon",
    value: 10,
    weight: 1,
    armor: null,
    abilities: [focusBolt(2, 4)],
    requiremnts: { strength: null, dexterity: null, constitution: null, intelligence: 5 },
  },
  {
    name: "Worn Leather Cap",
    type: "helmet",
    value: 4,
    weight: 1,
    armor: 1,
    abilities: [],
    requiremnts: {},
  },
  {
    name: "Padded Vest",
    type: "armor",
    value: 6,
    weight: 3,
    armor: 2,
    abilities: [],
    requiremnts: { strength: 3, dexterity: null, constitution: null, intelligence: null },
  },
  {
    name: "Traveler Ring",
    type: "ring",
    value: 5,
    weight: 0,
    armor: 0,
    abilities: [],
    requiremnts: {},
  },

  {
    name: "Iron Longsword",
    type: "weapon",
    value: 15,
    weight: 3,
    armor: null,
    abilities: [slash(3, 6), strike(2, 5)],
    requiremnts: { strength: 5, dexterity: 4, constitution: null, intelligence: null },
  },
  {
    name: "Steel Broadsword",
    type: "weapon",
    value: 25,
    weight: 4,
    armor: null,
    abilities: [cleave(4, 7), slash(3, 6)],
    requiremnts: { strength: 7, dexterity: 3, constitution: null, intelligence: null },
  },
  {
    name: "Elven Blade",
    type: "weapon",
    value: 20,
    weight: 2,
    armor: null,
    abilities: [slash(3, 5), rend(2, 4)],
    requiremnts: { strength: 4, dexterity: 6, constitution: null, intelligence: null },
  },
  {
    name: "Greatsword",
    type: "weapon",
    value: 35,
    weight: 5,
    armor: null,
    abilities: [whirlwind(5, 8), cleave(4, 7)],
    requiremnts: { strength: 8, dexterity: 2, constitution: null, intelligence: null },
  },

  {
    name: "Battle Axe",
    type: "weapon",
    value: 22,
    weight: 4,
    armor: null,
    abilities: [crush(4, 6), hack(3, 5)],
    requiremnts: { strength: 6, dexterity: 3, constitution: null, intelligence: null },
  },
  {
    name: "War Hammer",
    type: "weapon",
    value: 28,
    weight: 5,
    armor: null,
    abilities: [pummel(5, 8), crush(3, 6)],
    requiremnts: { strength: 8, dexterity: 2, constitution: null, intelligence: null },
  },
  {
    name: "Throwing Axe",
    type: "weapon",
    value: 18,
    weight: 2,
    armor: null,
    abilities: [slash(3, 5), pierce(2, 4)],
    requiremnts: { strength: 5, dexterity: 5, constitution: null, intelligence: null },
  },

  {
    name: "Longbow",
    type: "weapon",
    value: 20,
    weight: 2,
    armor: null,
    abilities: [arrow(3, 6), volley(4, 7)],
    requiremnts: { strength: null, dexterity: 6, constitution: null, intelligence: null },
  },
  {
    name: "Crossbow",
    type: "weapon",
    value: 25,
    weight: 3,
    armor: null,
    abilities: [pierceShot(5, 8), snipe(4, 7)],
    requiremnts: { strength: 5, dexterity: 5, constitution: null, intelligence: null },
  },
  {
    name: "Shortbow",
    type: "weapon",
    value: 15,
    weight: 1,
    armor: null,
    abilities: [arrow(2, 4), multishot(3, 6)],
    requiremnts: { strength: 3, dexterity: 6, constitution: null, intelligence: null },
  },

  {
    name: "Fire Staff",
    type: "weapon",
    value: 30,
    weight: 2,
    armor: null,
    abilities: [fireball(5, 8), inferno(6, 9)],
    requiremnts: { strength: null, dexterity: null, constitution: null, intelligence: 7 },
  },
  {
    name: "Frost Staff",
    type: "weapon",
    value: 30,
    weight: 2,
    armor: null,
    abilities: [blizzard(5, 8), freeze(4, 6)],
    requiremnts: { strength: null, dexterity: null, constitution: null, intelligence: 7 },
  },
  {
    name: "Lightning Rod",
    type: "weapon",
    value: 28,
    weight: 2,
    armor: null,
    abilities: [chainLightning(4, 7), thunder(3, 6)],
    requiremnts: { strength: null, dexterity: null, constitution: null, intelligence: 7 },
  },
  {
    name: "Poison Scepter",
    type: "weapon",
    value: 25,
    weight: 2,
    armor: null,
    abilities: [toxicCloud(4, 7), venom(3, 6)],
    requiremnts: { strength: null, dexterity: null, constitution: null, intelligence: 6 },
  },
  {
    name: "Healing Staff",
    type: "weapon",
    value: 35,
    weight: 2,
    armor: null,
    abilities: [greaterHeal(6, 10), regenerate(5, 8)],
    requiremnts: { strength: null, dexterity: null, constitution: null, intelligence: 8 },
  },

  {
    name: "Iron Helm",
    type: "helmet",
    value: 12,
    weight: 2,
    armor: 2,
    abilities: [],
    requiremnts: { strength: 4, dexterity: null, constitution: null, intelligence: null },
  },
  {
    name: "Dragon Helm",
    type: "helmet",
    value: 40,
    weight: 3,
    armor: 4,
    abilities: [],
    requiremnts: { strength: 7, dexterity: null, constitution: 6, intelligence: null },
  },
  {
    name: "Crown of Wisdom",
    type: "helmet",
    value: 50,
    weight: 1,
    armor: 2,
    abilities: [],
    requiremnts: { strength: null, dexterity: null, constitution: null, intelligence: 8 },
  },

  {
    name: "Steel Armor",
    type: "armor",
    value: 18,
    weight: 5,
    armor: 3,
    abilities: [],
    requiremnts: { strength: 5, dexterity: null, constitution: null, intelligence: null },
  },
  {
    name: "Mage Robes",
    type: "armor",
    value: 20,
    weight: 2,
    armor: 1,
    abilities: [],
    requiremnts: { strength: null, dexterity: null, constitution: null, intelligence: 6 },
  },
  {
    name: "Plate Armor",
    type: "armor",
    value: 35,
    weight: 6,
    armor: 5,
    abilities: [],
    requiremnts: { strength: 8, dexterity: null, constitution: 6, intelligence: null },
  },

  {
    name: "Iron Greaves",
    type: "leggings",
    value: 14,
    weight: 3,
    armor: 2,
    abilities: [],
    requiremnts: { strength: 5, dexterity: null, constitution: null, intelligence: null },
  },
  {
    name: "Shadow Leggings",
    type: "leggings",
    value: 16,
    weight: 2,
    armor: 2,
    abilities: [],
    requiremnts: { strength: null, dexterity: 6, constitution: null, intelligence: null },
  },
  {
    name: "Reinforced Boots",
    type: "leggings",
    value: 12,
    weight: 2,
    armor: 1,
    abilities: [],
    requiremnts: {},
  },

  {
    name: "Ring of Strength",
    type: "ring",
    value: 25,
    weight: 0,
    armor: 0,
    abilities: [],
    requiremnts: {},
  },
  {
    name: "Ring of Intelligence",
    type: "ring",
    value: 25,
    weight: 0,
    armor: 0,
    abilities: [],
    requiremnts: {},
  },
  {
    name: "Healing Ring",
    type: "ring",
    value: 30,
    weight: 0,
    armor: 1,
    abilities: [heal(3, 5)],
    requiremnts: {},
  },
  {
    name: "Ring of Protection",
    type: "ring",
    value: 28,
    weight: 0,
    armor: 2,
    abilities: [],
    requiremnts: {},
  },

  {
    name: "Duelist Rapier",
    type: "weapon",
    value: 26,
    weight: 1,
    armor: null,
    abilities: [riposte(3, 5), pierce(2, 4), dodge(1, 2)],
    requiremnts: { strength: 3, dexterity: 7, constitution: null, intelligence: null },
  },
  {
    name: "Mage Killer Blade",
    type: "weapon",
    value: 32,
    weight: 2,
    armor: null,
    abilities: [impale(4, 7), silence(2, 3), stun(2, 3)],
    requiremnts: { strength: 5, dexterity: 5, constitution: null, intelligence: null },
  },
  {
    name: "Holy Mace",
    type: "weapon",
    value: 28,
    weight: 3,
    armor: null,
    abilities: [smite(4, 6), blessing(3, 5), heal(2, 4)],
    requiremnts: { strength: 6, dexterity: null, constitution: null, intelligence: 5 },
  },
];

/** Seeds items records into the database. */
export const seed = async () => {
  const inserted = await db
    .insert(schema.item)
    .values(ITEMS)
    .onConflictDoNothing({ target: schema.item.name })
    .returning({ id: schema.item.id });
};
