#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🔍 Checking code format..."
if ! bunx prettier --check .; then
  echo "🪄 Formatting code..."
  bunx prettier --write .

  echo "📦 Adding formatted files..."
  git add .

  echo "💬 Committing format fixes..."
  git commit -m "chore: format code"

  echo "🚀 Pushing formatted changes..."
  git push
else
  echo "✅ Code already formatted. Proceeding with push."
fi
